### ISSUE TITLE
error maybe due to new version?

### ISSUE THREAD

**Issue by vortex91** [tremby/jellyfin-find-duplicates#2]
I get error when running
parse error: Invalid numeric literal at line 1, column 7
[DEBUG] USER_ID=
parse error: Invalid numeric literal at line 1, column 7
[DEBUG] LIB_ID=
parse error: Invalid numeric literal at line 1, column 7
[DEBUG] SERIES_IDS=

is it compatible with jellyfin 10.9.2?

**Comment by tremby** [comment]
I'm on that version and it's working for me. Your error messages make it look like it wasn't able to get valid responses from jellyfin or wasn't able to process them. Do you have the dependencies installed, like jq? You're sure the API is enabled and you have the right key etc configured?

If I were you I'd tweak the script a little to output the result of those requests (lines 103 to 105) before they're passed to jq; there might be some useful error output.

Let me know if you need help with that.

Whatever the issue is, I should build something in to signpost it better to the user. Patches welcome if you're up to it, or I can do it if we discover what the issue is.

**Comment by vortex91** [comment]
got it working.  Thanx for info.

can we edit this to work on movies also?

**Comment by tremby** [comment]
> got it working. Thanx for info.

What was the issue? If there's a spot where I could put better error messaging I'd like to.

> can we edit this to work on movies also?

I've got no need for that personally but patches welcome...

**Comment by vortex91** [comment]
The issue was I renamed the script to end with .sh 
i renamed it back to original error went away.

If you want to make script a bit more robust it seems like it finds dupes for Season 00 due to unconventional naming.  An optoin to skip any subfolders Season 00 would be nice to have. (i might look into this myself and provide it in a few days)
